### ISSUE TITLE
2024-10-16 version - live stream and HTML panels do not expand to full screen with double clicked

### ISSUE THREAD

**Issue by midair55** [VA3HDL/hamdashboard#31]
Love the enhancement of being able to have streaming and HTML in the panels!

Reference bottom right panel at: https://qsl.net/n5ng/beta   The first image is a live camera stream (it does not autoplay but that's an issue with YouTube....).  It will manually start when clicking on on the image but will not expand when double clicked.  The images do rotate but it seems the live stream 'start' images doesn't always appear in the rotation.  This is seen when allowed to auto-rotate and right click to rotate.

The bottom 3rd panel first definition is an HTML file followed by still images.  Likewise the HTML does not expand to full screen and not seen in the rotation when manually rotated.

**Comment by VA3HDL** [comment]
Mixing content (websites, images, and videos) on the tiles is allowed. However, the mouse inputs only works with images (manual rotate, zoom, expand, etc.) The reason is websites and videos on the tiles handles mouse events themselves. I was aware of this and is intentional. 

Now regarding the autostart of YouTube videos, your URL is:
iframe|https://www.youtube.com/embed/FTw5xuq2swo?si=jNiQRYDfl37RElao?autoplay=1

I use this one:
iframe|https://www.youtube.com/embed/fzPFaXAV_2Y?autoplay=1&mute=1

Note that you have two "?" on the URL. This seems to be the reason for the autostart to play to fail.

**Comment by midair55** [comment]
Pablo - Thanks for the quick response
Understood on the media type mixing and mouse inputs.

Interesting how a missing "?mute=1" causes the YouTube video not to play.
